### ISSUE TITLE
Error 404 404

### ISSUE THREAD

**Issue by Dantzi** [ndahlquist/stable-horde-flutter#126]
![Screenshot_20230302_005315](https://user-images.githubusercontent.com/111058188/222251241-d59c07c1-a371-481e-b102-c8b929a12af3.jpg)
Ability to select ai model has disappeared. Is this the only one I have?

**Comment by Elijah629** [comment]
I asked about this on the discord, there was an emergency change and the model reference in stable horde got relocated overnight, this is a bug. You can use the web interface while the dev fixes it.
