### ISSUE TITLE
Add option to donate images

### ISSUE THREAD

**Issue by ndahlquist** [ndahlquist/stable-horde-flutter#66]
"as per the RFC I opened (https://discord.com/channels/781145214752129095/1060881403459407902), we have now switched to opt-in sharing images. You can now send "shared: true" in your requests, to make the horde share them with LAION. 

Remember that anonymous accounts automatically shares them! 

Also note that we will never share img2img or inpainting results!

@Stable Horde: Integrator: Please look into adding the switch for the new key and explain what it does. Furthermore, if you are reporting kudos costs for each generation, please adjust each image by +3 when share==False, and +1 when share==true. "

**Comment by ndahlquist** [comment]
Suggested UX:
- A new switch in settings.
- "Donate generated images": "Share your prompts and generated images to aid in training future versions of Stable Diffusion."
- Default on. If user attempts to disable while not logged in: "All images from anonymous users are donated. To turn off donation, create a Stable Horde account."

**Comment by Khosbayar** [comment]
Working on this week
